proxy:
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  https:
    enabled: true
    type: letsencrypt
    hosts:
      - local.jovyan.org
    letsencrypt:
      contactEmail: "jovyan@jupyter.test"
      acmeServer: https://pebble/dir
  traefik:
    extraVolumes:
      - name: pebble-root-cert
        configMap:
          name: pebble
    extraVolumeMounts:
      - name: pebble-root-cert
        subPath: root-cert.pem
        mountPath: /etc/pebble/root-cert.pem
    extraEnv:
      LEGO_CA_CERTIFICATES: /etc/pebble/root-cert.pem
  chp:
    resources:
      requests:
        memory: 0
        cpu: 0
    networkPolicy:
      egress: [] # overrides allowance of 0.0.0.0/0

hub:
  db:
    type: sqlite-memory
  services:
    test:
      admin: true
      apiToken: ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
  networkPolicy:
    egress: # overrides allowance of 0.0.0.0/0
      # In kind/k3s clusters the Kubernetes API server is exposing this port
      - ports:
          - protocol: TCP
            port: 6443
  resources:
    requests:
      memory: 0
      cpu: 0
  extraFiles:
    my_config:
      mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/my_config.py
      stringData: |
        with open("/tmp/created-by-extra-files-config.txt", "w") as f:
            f.write("hello world!")
    binaryData1: &binaryData1
      mountPath: /tmp/binaryData.txt
      mode: 0666
      binaryData: |
        aGVsbG8gd
        29ybGQhCg==
    binaryData2: &binaryData2
      mountPath: /tmp/dir1/binaryData.txt
      mode: 0666
      binaryData: aGVsbG8gd29ybGQhCg==
    stringData1: &stringData1
      mountPath: /tmp/stringData.txt
      mode: 0666
      stringData: hello world!
    stringData2: &stringData2
      mountPath: /tmp/dir1/stringData.txt
      mode: 0666
      stringData: hello world!
    data-yaml: &data-yaml
      mountPath: /etc/test/data.yaml
      mode: 0444
      data:
        config:
          map:
            number: 123
            string: "hi"
          list: [1, 2]
    data-yml: &data-yml
      <<: *data-yaml
      mountPath: /etc/test/data.yml
    data-json: &data-json
      <<: *data-yaml
      mountPath: /etc/test/data.json
    data-toml: &data-toml
      <<: *data-yaml
      mountPath: /etc/test/data.toml

singleuser:
  extraFiles:
    binaryData1: *binaryData1
    binaryData2: *binaryData2
    stringData1: *stringData1
    stringData2: *stringData2
    data-yaml: *data-yaml
    data-yml: *data-yml
    data-json: *data-json
    data-toml: *data-toml
  storage:
    type: none
  memory:
    guarantee: null
  networkPolicy:
    # For testing purposes in test_singleuser_netpol
    egress:
      - to:
          # jupyter.org has multiple IPs associated with it, among them are these
          # two. We explicitly allow access to one, but leave out the the other.
          - ipBlock:
              cidr: 104.28.8.110/32
        # - ipBlock:
        #     cidr: 104.28.9.110/32
  extraEnv:
    TEST_ENV_FIELDREF_TO_NAMESPACE:
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

prePuller:
  hook:
    enabled: false

scheduling:
  userScheduler:
    enabled: true
    replicas: 2
    logLevel: 10

debug:
  enabled: true
